### ISSUE TITLE
Missing template-body cfn-custom-resource-provider.json

### ISSUE THREAD

**Issue by onhate** [binxio/cfn-mysql-user-provider#2]
Hi, I'm following the steps in the readme willing to setup the mysql user provider, but I noticed that the documentation mentions `--template-body file://cloudformation/cfn-custom-resource-provider.json` but I could not find this file in the project or any other reference to it.

How does it works to generate/gather this file?

**Comment by mvanholsteijn** [comment]
Oops, I forgot to update the readme. the cloudformation templates were changed to yaml. I just updated the README.
